### ISSUE TITLE
[FEAT] 추천 기능

### ISSUE THREAD

**Issue by SEMINSEMINSEMIN** [SEMINSEMINSEMIN/pre-onboarding-10th-4-2#21]
## TODO
- [ ] search api 만들기
- [ ] Input에 500ms로 debounce를 적용
- [ ] Dropdown에 추천된 아이템들이 처음에 10개가 나올 수 있도록
- [ ] 아이템이 더 있으면 무한 스크롤로 최대 10개씩 받아올 수 있도록
- [ ] Dropdown에서 아이템 하나를 선택하면, input의 value는 초기화가 되고 아이템이 리스트에 추가되도록
- [ ] 드랍다운 UI
  - [ ] 검색 시 드랍다운 및 드랍다운 내역에서 검색어가 색상으로 활성화
  - [ ] 검색 시 드랍다운 내 호버 및 클릭 상황
  - [ ] 검색 시 드랍다운 내용이 길 때, 스크롤 하단에 표시 아이콘
  - [ ] 검색 내용이 로딩될 때 무한 로딩 스피너
